spring.application.name=backend

# JDBC URL to RDS MySQL DB
spring.datasource.url=jdbc:mysql://petals-db.cjyw8w4smg3y.us-east-2.rds.amazonaws.com:3306/petals_db

# Credentials 
spring.datasource.username=admin
spring.datasource.password=Petals8925

# JPA / Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Stock management configuration
app.stock.low-threshold=10
app.stock.critical-threshold=3

